version: "3.2"
services:
    nginx:
        build: .
        links:
            - "api"
        ports:
            - "80:80"
        tty: true
    api:
        build: 
            dockerfile: DockerfileJS
            context: .
       # ports:
        #    - "3000:3000"
