version: "3.2"

services:
    nginx:
        image: kermansanjuan/nginx-as
        links:
            - "api"
        ports:
            - "80:80"
        tty: true

    api:
        image: kermansanjuan/express-as
        volumes:
          - ./nodejs:/code

       # ports:
        #    - "3000:3000"
