apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: api
    spec:
      containers:
        - image: kermansanjuan/express-as
          name: api
          ports:
            - containerPort: 3000
      restartPolicy: Always