apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
        - image: kermansanjuan/express-as
          name: api
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /code
              name: api-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /Users/kerman/Documents/GitHub/Sistemas-Proyecto-Individual/kubernetes/nodejs
          name: api-hostpath0
status: {}
