apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nginx
  strategy: {}
  template:
    metadata:
      labels:
        service: nginx
    spec:
      containers:
        - image: kermansanjuan/nginx-as
          name: nginx
          ports:
            - containerPort: 80
          resources: {}
          tty: true
      restartPolicy: Always
status: {}
